spring:
  application:
    name: VectoPath

  # Configuration de la base de données PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/vecto_path
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  # Configuration Spring AI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:demo}
      embedding:
        model: text-embedding-3-small
        options:
          model: text-embedding-3-small

    # Configuration Spring AI Vector Store
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000

# Configuration du serveur
server:
  port: 8080

# Configuration JSON
spring.jackson:
  serialization:
    write-dates-as-timestamps: false
  time-zone: UTC

# Configuration des logs
logging:
  level:
    com.laulem.vectopath: INFO
    org.springframework.ai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
