spring:
  application:
    name: VectoPath

  datasource:
    url: jdbc:postgresql://localhost:5432/vecto_path
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:demo}
      embedding:
        model: text-embedding-3-small
        options:
          model: text-embedding-3-small

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000

server:
  port: 8080

spring.jackson:
  serialization:
    write-dates-as-timestamps: false
  time-zone: UTC

logging:
  level:
    com.laulem.vectopath: INFO
    org.springframework.ai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
